### ISSUE TITLE
MIME type is not executable

### ISSUE THREAD

**Issue by Khalahd** [jasonmayes/Twitter-Post-Fetcher#186] opened 2018-09-19 20:49 UTC
Hey, I'm seeing that this is a past issue from twitter changing their APIs, but it looks like it's happened again.
Noticed it on a site that uses your twitter fetcher, and looks like it's occurring on your codepen and on your example site http://jasonmayes.com/projects/twitterApi/ as well.

Full error:
`Refused to execute script from 'https://cdn.syndication.twimg.com/widgets/timelines/347099293930377217?&lang=en&callback=__twttrf.callback&suppress_response_codes=true&rnd=0.5912314472119449' because its MIME type ('') is not executable, and strict MIME type checking is enabled.`

Looks similar to issue #128 but it's not listing any MIME type in the error.

Wanted to let you know, keep up the great work! :-)

**Comment by bcmull** [comment] 2018-09-20 13:19
I am seeing something similar. Thanks @Khalahd for posting early.

**Comment by azcotic** [comment] 2018-09-20 13:27
Same here... Already trying hosting the min.js in rawgit.

**Comment by denisp1993** [comment] 2018-09-20 14:18
Hi! The CDN service used from this library is unavailable **https://cdn.syndication.twimg.com/** .

**Comment by adanielyan** [comment] 2018-09-20 16:00
Is there an alternative CDN anybody is aware of?

**Comment by DesignerDave** [comment] 2018-09-20 20:02
I think I've managed to make a temporary fix to the script. The URL this script constructs doesn't quite work anymore, but the CDN is still working.

In place of the line that constructs the CDN URL:
``` JavaScript
script.src = 'https://cdn.syndication.twimg.com/widgets/timelines/' +
              config.id + '?&lang=' + (config.lang || lang) +
              '&callback=__twttrf.callback&' +
              'suppress_response_codes=true&rnd=' + Math.random();
```

I wrote the following function:
``` JavaScript
function constructTwitterCDNUrl(params) {
  var urlParams = ''

  for (var param in params) {
    console.log(param)
    if (!urlParams.length) {
      urlParams += '?'
    }
    else {
      urlParams += '&'
    }

    urlParams += param + '=' + encodeURIComponent(params[param])
  }

  console.log(urlParams)

  // I'm loading a user's likes for my example
  return 'https://cdn.syndication.twitter.com/timeline/likes' + urlParams
}
```

Then I replaced the above line with:
``` JavaScript
script.src = constructTwitterCDNUrl({
  callback: '__twttrf.callback',
  dnt: 'false',
  domain: window.location.host,
  lang: (config.lang) || lang,
  suppress_response_codes: 'true',
  screen_name: <twitter username>,
  list_slug: 'likes',
});
```

This works for me. Hopefully this helps people who's timelines broke in the past day, and maybe helps with a more permanent fix.

**Comment by izzyartanddesign** [comment] 2018-09-20 21:07
DesignerDave,

What about if I'm currently using the configuration with the widget ID instead of a username/screen_name? I'm using the config option like so:

var config5 = {
  "id": '863044388271927297',
  "domId": '',
  "maxTweets": 4,
  "enableLinks": true,
  "showUser": true,
  "showTime": true,
  "dateFunction": dateFormatter,
  "showRetweet": true,
  "customCallback": handleTweets,
  "showInteraction": false,
  "showImages": true
};

Thanks

**Comment by DesignerDave** [comment] 2018-09-20 21:48
@izzyartanddesign,

I'm making some guesses here, but I think it is the widget API that changed and broke this. If you're attempting a similar solution to mine, the change you make to the script would depend on what kind of timeline/list your showing, and wouldn't touch the config.

If you're showing a timeline, the return in the function I wrote would probably simply be:
``` JavaScript
return 'https://cdn.syndication.twitter.com/timeline' + urlParams
```
Or if it's a list it might be something like:
``` JavaScript
return 'https://cdn.syndication.twitter.com/lists' + urlParams
```

You're gonna probably need to play around with the code I wrote a little bit to get it right for your use case. Hopefully this library is fixed in a way that can make a similar solution to mine more generic.

**Comment by jasonmayes** [comment] 2018-09-21 04:31
Your fix does indeed work. I shall merge that in for now. Cheers @DesignerDave

**Comment by jasonmayes** [comment] 2018-09-21 04:59
Oh wait, it has the same issue as my code no - it does not work for widget ids?

**Comment by jasonmayes** [comment] 2018-09-21 05:13
Unless anyone can find any way to maintain widgets I think the day has come to deprecate support for widget IDs. I dont see any evidence of their existence anymore? All my newer code samples still work for profile, lists, and likes using the new format that has been in TwitterFetcher for a while now.

**Closed by jasonmayes** 2018-09-21 05:13 UTC

**Comment by DesignerDave** [comment] 2018-09-21 17:29
@jasonmayes It doesn't work for widget IDs – I was originally using those too. I haven't spent a lot of time on this aside from getting the site I maintain working, but it looks a bit like they're being deprecated.

**Comment by timoa** [comment] 2018-09-22 14:59
I confirm what @jasonmayes tried and it works!

I replace the `id` (widget id) attribute by `screename` and it works without any changes under the JS file (still version 18)

**Comment by izzyartanddesign** [comment] 2018-09-24 13:57
Yup, I can confirm as well that it works when replacing widget ID attribute with screename.

Thanks so much guys.

**Comment by pierrebonbon** [comment] 2018-09-27 18:01
Same here. I was bumping into the very same issue. Replacing `"id": '1212122122121212',` with `"profile": {"screenName": 'my_screen_name'},` did the trick.

**Comment by sms20** [comment] 2018-10-01 09:18
I've switched from the Widget ID to using a profile which has done the trick. Can anyone confirm if they are able to disable retweets using the following `"showRetweet": false`

I don't seem to be able to hide re-tweets.

**Comment by tomwake** [comment] 2018-10-04 19:07
@jasonmayes I had a widget that pulled in all posts by hashtag - is this supported with the new format? I was unable to find an example.

**Comment by jasonmayes** [comment] 2018-10-07 21:09
No widgets have been removed from Twitter.

**Comment by adamhughes86** [comment] 2018-10-09 15:34
> I've switched from the Widget ID to using a profile which has done the trick. Can anyone confirm if they are able to disable retweets using the following `"showRetweet": false`
> 
> I don't seem to be able to hide re-tweets.

I had the `showRetweet` option still in my config and it was causing the Mime type issue for me. Removing that option fixed it
