### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by azappa** [jasonmayes/Twitter-Post-Fetcher#69] opened 2016-03-03 15:48 UTC
Hi, on my website (and on http://www.jasonmayes.com/projects/twitterApi/ too) the fetcher doesnt work anymore. Maybe some Twitter changes to API?

Thank you!

**Comment by ersgonzalo** [comment] 2016-03-03 15:58
Yeah, it seems like Twitter changed the way that their tweets are outputted from their widget. I'm looking into it for my own site as well.

**Comment by SiteSplat** [comment] 2016-03-03 16:00
yup broken. It just happened. I cant find any reference on their changes though.

**Comment by FooseTV** [comment] 2016-03-03 16:04
It was working as of yesterday evening as I was working with a new page and this script. Something happened between last night and this morning. I've confirmed that the Twitter account I'm using is generating widgets and using the same id codes but there's a disconnect between the script and the widgets.

**Comment by SiteSplat** [comment] 2016-03-03 16:11
https://twitter.com/SiteSplat/status/705421314748764160 tweet and retweet LOL

**Comment by minDGarden** [comment] 2016-03-03 16:24
I noticed it stopped working today too.

**Comment by xecollons** [comment] 2016-03-03 16:25
Same here. The plugin is getting the widget body, but it seems that the tweets have different classes.

**Comment by scopeak** [comment] 2016-03-03 16:44
+1 down for me too today.

**Comment by FooseTV** [comment] 2016-03-03 16:50
I concur. I believe Twitter changed all the class names of the HTML elements on the widget. Nothing matches the classes the script is trying to grab.

**Comment by ersgonzalo** [comment] 2016-03-03 16:57
Yeah, I have a sort of working demo that I used with inspiration from ng-tweets, which also used jQuery. (*sorry*) It's sort of working on my own site now but jasonmayes' fetcher was built using vanilla. Maybe if you replace some of the scripts then it will work better

```
if (data._body) {
        els = $(data._body.body)[0].getElementsByClassName('timeline-Tweet');
        for (x = 0; x < els.length; x++) {
          el = els[x];
          tweet = {};
          tweet.retweet = (el.getElementsByClassName('timeline-Tweet-retweetCredit').length > 0);
          tweet.id = el.getAttribute('data-tweet-id');
          tmp = el.getElementsByClassName('timeline-Tweet-text')[0];
          tweet.title = tmp.innerHTML;
          tweet.text = tmp.textContent || tmp.innerText; // IE8 doesn't support textContent
          tmp = el.getElementsByClassName('timeline-Tweet-author')[0];
          tweet.author = {
            url: tmp.getElementsByClassName('TweetAuthor-link')[0].getAttribute('href'),
            avatar: tmp.getElementsByClassName('Avatar')[0].getAttribute('data-src-1x'),
            fullName: tmp.getElementsByClassName('TweetAuthor-name')[0].innerText,
            nickName: tmp.getElementsByClassName('TweetAuthor-screenName')[0].innerText
          };
          tweet.updated = el.getElementsByClassName('dt-updated')[0].innerText;
          tweet.link = el.getElementsByClassName('timeline-Tweet-timestamp')[0].getAttribute('href');
        //  if (el.getElementsByClassName('inline-media')[0]) {
        //    tweet.inlineMedia = el.getElementsByClassName('inline-media')[0].innerHtml;
        //  }
          response.tweets.push(tweet);
        }
      }
```

You can check my full gist here for help: https://gist.github.com/ersgonzalo/05108bf7550e2f8e4b6f

**Comment by xecollons** [comment] 2016-03-03 17:00
Finishing my function too, very very simple(only last tweet, no rts, no images) for my site, will post the code here later.

**Comment by SiteSplat** [comment] 2016-03-03 17:17
Things changed a bit. here it is: https://blog.twitter.com/2016/coming-soon-an-improved-embedded-timeline

**Comment by FooseTV** [comment] 2016-03-03 17:40
It also appears they changed they way media is displayed as well. There seems to be a series of new "MediaCard" classes.

**Comment by jasonmayes** [comment] 2016-03-03 17:54
Yep Twitter has changed classes. Will look into this

**Comment by xecollons** [comment] 2016-03-03 17:55
Ok, at the end, for the people like me, that doesn't need images, it's a simple change of classes in the source code:


class 'tweet' = 'timeline-Tweet'
class 'e-entry-title' = 'timeline-Tweet-text'
class 'p-author' = 'timeline-Tweet-author'
class 'permalink' = 'timeline-Tweet-timestamp'

With that, I have made it work. I still have to look how to adapt twitter links with elipsis and all.

**Comment by rawksteady** [comment] 2016-03-03 17:56
@jasonmayes Great to hear. If I'm not being too pushy, would this be a good time to maybe looking into this https://github.com/jasonmayes/Twitter-Post-Fetcher/pull/48 as well?

**Comment by jasonmayes** [comment] 2016-03-03 18:15
This is now fixed. Please grab v15 from github. Thanks guys for your support and suggestions.

**Closed by jasonmayes** 2016-03-03 18:15 UTC

**Comment by jasonmayes** [comment] 2016-03-03 18:17
@rawksteady Hey can you give me a widget id which has some retweets in? I almost never retweet myself :-) I can see what this produces.

**Comment by rawksteady** [comment] 2016-03-03 18:25
@jasonmayes 402038497487224832 First entry should be a retweet

**Comment by jasonmayes** [comment] 2016-03-03 18:46
It is not, it is a regular tweet. If you could do a few retweets so I can check that would be helpful. Thanks.

**Comment by rawksteady** [comment] 2016-03-03 18:51
I did 2 or 3 of them just now.

**Comment by azappa** [comment] 2016-03-03 18:52
A little bit off topic, do you have plan to publish your lib on cdnjs.com?

**Comment by jasonmayes** [comment] 2016-03-03 19:16
@rawksteady Ive just realised using advanced example where by you ask for dataOnly you can discover if rt or not and then simply add a class yourself. This is possible already:
```
var config = {
  "id": '502160051226681344',
  "dataOnly": true,
  "customCallback": populateTpl,
  "maxTweets": 5
};

twitterFetcher.fetch(config);

function populateTpl(tweets){
  console.log(tweets);
}
```

**Comment by jasonmayes** [comment] 2016-03-03 19:17
@azappa I did not, but feel free to request to add it if you want it there via their request form.

**Comment by Joel-Mercier** [comment] 2016-03-04 09:36
Thank you so much @jasonmayes for fixing this so quickly !

**Comment by rorysmorris** [comment] 2016-03-04 11:01
Thanks for the fast fix. Now, to push this new JS file to 100+ sites!

Maybe we should deliver plugins like this from a CDN. Any suggestions anyone?

**Comment by minDGarden** [comment] 2016-03-04 15:44
@jasonmayes Thanks for the quick fix!

**Comment by jasonmayes** [comment] 2016-03-05 00:29
No problem. Happy it has helped so many!
