### ISSUE TITLE
Issue with the Twitter.js 1.7.0.0 and possibly 

### ISSUE THREAD

**Issue by harry-takhar** [jasonmayes/Twitter-Post-Fetcher#169] opened 2018-03-29 10:21 UTC
There is an issue with the avatarImg being undefined so when the element is being passed into the function there is no img tag in the DOM.

At the moment this is fixed I had to do to ensure it does not break on our companies intranet site.
```
      function swapDataSrc(element) {
        var avatarImg = element.getElementsByTagName('img')[0] !== undefined ? element.getElementsByTagName('img')[0] : "";
            avatarImg.src = avatarImg !== "" ? avatarImg.getAttribute('data-src-2x') : "";
        return element;
      }
```

In 1.7.0.3 the code below throws an error as cannot read getAttribute of null in the console.log of Google Chrome

```
profile_image: authors[n] ? authors[n].querySelector('[data-scribe="element:avatar"]').getAttribute('data-src-1x') : null,
profile_image_2x: authors[n] ? authors[n].querySelector('[data-scribe="element:avatar"]').getAttribute('data-src-2x') : null,
```

**Comment by kauffmanes** [comment] 2018-03-29 12:52
I had to comment those last two profile lines out for it to actually work.

**Comment by bmcorey** [comment] 2018-03-29 16:18
Fixed,
There's a problem with the `function swapDataSrc()`, 
Commenting the line 224 in twitterFetcher.js or in line 41 in the min.js will fix the problem and you can make it work at the moment

**Comment by harry-takhar** [comment] 2018-03-29 16:41
I have manage to fix but created a pull request to get it resolved in the repo it was working fine yesterday unless there was a change to the code that broke it.

**Comment by jasonmayes** [comment] 2018-03-30 02:56
Thank you all this is a duplicate of other reports. A fix is in progress but it appears profile images are no longer in the returned HTML. Any of you figured out how to keep profile images showing?

**Comment by jasonmayes** [comment] 2018-03-30 03:35
I have written a a patch to deal with the image issue too. Please update to v18.0.0

**Closed by jasonmayes** 2018-03-30 03:35 UTC
Labels: duplicate
